/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hangman;

public class App {
  
  /**
    public String getGreeting() {
        //return "Hello World!";
    }
  */

    public static void main(String[] args) {

        //Game hangman1 = new Game(10);

        //System.out.println(hangman1.getRandomWordFromDictionary());

        //System.out.println(hangman1.getWordToGuess());



    }
}
